import Footer from './components/Footer';
import Header from './components/Header';

import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700']
})

export const metadata = {
  title: 'Nextjs App',
  description: 'Generated by Meem',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>

        <div className='max-w-4xl mx-auto px-5'>
          <Header></Header>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
